-- 한 줄 주석

-- 비밀번호 설정까지 한번에 하는 일반 사용자 계정 생성 문 (오직 관리자 계정에서만 사용할 수 있음)
-- [표현법] : CREATE USER 계정명 IDENTIFIED BY 비밀번호; (계정명 앞에 c##을 붙이면 공통계정)
CREATE USER c##SERVER IDENTIFIED BY SERVER;
-- SQL은 대소문자를 구분하지 않음 다만 비밀번호는 대소문자를 구분함

--위에서 생성된 일반 사용자 계정에 최소한의 권한 (접속, 데이터관리) 부여
-- [표현법] : GRANT 권한1, 권한2, ... TO 계정;
GRANT CONNECT, RESOURCE TO c##SERVER;

ALTER USER c##SERVER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##TEST IDENTIFIED BY TEST;
-- SQL은 대소문자를 구분하지 않음 다만 비밀번호는 대소문자를 구분함

--위에서 생성된 일반 사용자 계정에 최소한의 권한 (접속, 데이터관리) 부여
-- [표현법] : GRANT 권한1, 권한2, ... TO 계정;
GRANT CONNECT, RESOURCE TO C##TEST;
ALTER USER C##TEST DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE VIEW TO C##TEST;


CREATE USER C##INDEXTEST IDENTIFIED BY INDEXTEST;
GRANT CONNECT, RESOURCE TO C##INDEXTEST;
ALTER USER C##INDEXTEST DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##JDBC IDENTIFIED BY JDBC;
GRANT CONNECT, RESOURCE TO C##JDBC;
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


CREATE USER C##JSP IDENTIFIED BY JSP;
GRANT CONNECT, RESOURCE TO C##JSP;
ALTER USER C##JSP DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##MYBATIS IDENTIFIED BY MYBATIS;
GRANT CONNECT, RESOURCE TO C##MYBATIS;
ALTER USER C##MYBATIS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##SPRING IDENTIFIED BY SPRING;
GRANT CONNECT, RESOURCE TO C##SPRING;
ALTER USER C##SPRING DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;