-- 1
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", 
    CASE
    WHEN SUBSTR(ENTRANCE_DATE, 1, 2) BETWEEN '00' AND '26'
    THEN TO_CHAR(TO_DATE('20' || ENTRANCE_DATE, 'YY/MM/DD'), 'YYYY-MM-DD')
    ELSE TO_CHAR(TO_DATE('19' || ENTRANCE_DATE, 'YY/MM/DD'), 'YYYY-MM-DD')
    END AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ASC;

-- 2 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3
SELECT PROFESSOR_NAME AS "교수 이름",FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19||SUBSTR(PROFESSOR_SSN, 1, 6), 'YYMMDD'))/ 12) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

-- 4
SELECT SUBSTR(PROFESSOR_NAME, 2) AS "이름"
FROM TB_PROFESSOR;

-- 5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN (SELECT STUDENT_NO,
                      CASE
                       WHEN SUBSTR(ENTRANCE_DATE, 1, 2) BETWEEN '00' AND '49' THEN
                       TRUNC(MONTHS_BETWEEN(TO_DATE('20' || ENTRANCE_DATE, 'YYYY/MM/DD'), TO_DATE('19' || SUBSTR(STUDENT_SSN, 1, 6), 'YYYYMMDD')) / 12)
                      ELSE 
                      TRUNC(MONTHS_BETWEEN(TO_DATE('19' || ENTRANCE_DATE, 'YYYY/MM/DD'), TO_DATE('19' || SUBSTR(STUDENT_SSN, 1, 6), 'YYYYMMDD')) / 12)
                      END AS "AGE"
                     FROM TB_STUDENT) USING (STUDENT_NO)
WHERE AGE <20;             

-- 6
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY') AS "2020년 크리스마스"
FROM DUAL;

-- 7
--TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD')
--은 각각 2099년 10월 11일하고 2049년 10월 11일을 나타냅니다
--TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
--은 각각 1999년 10월 11일하고 2049년 10월 11일을 나타냅니다.

-- 8
SELECT SUBSTR(STUDENT_NO,2) AS "학번",  STUDENT_NAME AS "이름"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

-- 9
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
SELECT  DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12
SELECT SUBSTR(TERM_NO,1,4) AS "년도", ROUND(POINT,1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';

-- 13
SELECT DEPARTMENT_NO AS "학과코드명", COUNT(*) AS "휴학생 수"
FROM (SELECT DEPARTMENT_NO, ABSENCE_YN
      FROM TB_STUDENT
      WHERE ABSENCE_YN ='Y')
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14
SELECT STUDENT_NAME AS "동일이름", COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >1;

-- 15
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", SUBSTR(TERM_NO, 5, 2) AS "학기", ROUND(POINT,1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';

SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);

SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';




