-- 1
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);

INSERT INTO TB_CLASS_TYPE
VALUES(01, '전공필수');
INSERT INTO TB_CLASS_TYPE
VALUES(02, '전공선택');
INSERT INTO TB_CLASS_TYPE
VALUES(03, '교양필수');
INSERT INTO TB_CLASS_TYPE
VALUES(04, '교양선택');
INSERT INTO TB_CLASS_TYPE
VALUES(05, '논문지도');

-- 2
CREATE TABLE TB_STUDENT_INFO
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT);

-- 3
CREATE TABLE TB_KOL_INFO
AS (SELECT S.STUDENT_NO AS "학번", S.STUDENT_NAME AS "학생이름", (1900 + SUBSTR(S.STUDENT_SSN, 1, 2)) AS "출생년도", NVL(P.PROFESSOR_NAME, '미배정') AS "교수 이름"
    FROM TB_STUDENT S
    JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
    LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
    WHERE D.DEPARTMENT_NAME = '국어국문학과');
 
SELECT S.STUDENT_NO AS "학번", S.STUDENT_NAME AS "학생이름", (1900 + SUBSTR(S.STUDENT_SSN, 1, 2)) AS "출생년도", NVL(P.PROFESSOR_NAME, '미배정') AS "교수 이름"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE D.DEPARTMENT_NAME = '국어국문학과';

-- 4
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND((CAPACITY*0.1) + CAPACITY);

-- 5
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

-- 6
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SWSN, 1, 6);

-- 7
UPDATE TB_GRADE
SET POINT = 3.5
WHERE STUDNET_NAME = '김명훈'
AND STUDENT_NO = (SELECT STUDNET_NO
                  FROM TB_STUDENT
                  JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                  WHERE DEPARTMENT_NAME = '의학과'
                  AND STUDENT_NAME = '김명훈')
AND CLASS_NO = (SELECT CLASS_NO
                FROM TB_CLASS
                WHERE CLASS_NAME = '피부생리학')
AND TERM_NO = '200501';

/*
SELECT STUDENT_NAME, DEPARTMENT_NAME, POINT, TERM_NO, CLASS_NAME
FROM TB_STUDENT
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(STUDENT_NO)
     JOIN TB_CLASS USING(CLASS_NO)
WHERE STUDENT_NAME = '김명훈'
      AND DEPARTMENT_NAME = '의학과'
      AND TERM_NO LIKE '2005%'
      AND CLASS_NAME = '피부생리학'; -- 1.5
*/
-- 8
DELETE FROM TB_GRADE_TEST
WHERE STUDENT_NO = (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');


