DROP TABLE TB_MEMBER;
DROP TABLE TB_BOOK;

CREATE TABLE TB_BOOK(
BK_NO NUMBER CONSTRAINT BOOK_PK PRIMARY KEY,
BK_TITLE VARCHAR2(50) CONSTRAINT BOOK_NN_TITLE NOT NULL,
BK_AUTHOR VARCHAR2(20) CONSTRAINT BOOK_NN_AUTHOR NOT NULL,
BK_NUM NUMBER,
BK_PRICE NUMBER,
BK_PUB_NO VARCHAR2(20)
);    

CREATE TABLE TB_MEMBER (
MEMBER_NO NUMBER CONSTRAINT MEMBER_PK PRIMARY KEY, --MEMBER_NO(회원번호) 기본키(MEMBER_PK)
MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_UQ_ID UNIQUE, --MEMBER_ID(아이디)(MEMBER_UQ_ID)
MEMBER_PWD VARCHAR2(20) CONSTRAINT MEMBER_NN_PWD NOT NULL, --MEMBER_PWD(비밀번호)(MEMBER_NN_PWD)
MEMBER_NAME VARCHAR2(20) CONSTRAINT MEMBER_NN_NAME NOT NULL, --MEMBER_NAME(회원명)(MEMBER_NN_NAME)
GENDER CHAR(3) CONSTRAINT MEMBER_CK_GNE CHECK(GENDER IN('M', 'F')), --GENDER(성별)(MEMBER_CK_GEN)
ADDRESS VARCHAR(50), --ADDRESS(주소)
PHONE VARCHAR(13), -- PHONE(연락처)
ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL --ENROLL_DATE(가입일) (MEMBER_NN_EN)
);
            
CREATE TABLE TB_MEMBER_BOOK (
    MEMBER_NO NUMBER,                      -- 회원 번호 (FK)
    BK_NO NUMBER,                          -- 도서 번호 (FK)
    PURCHASE_DATE DATE DEFAULT SYSDATE,     -- 구매 일자 (기본 값: 현재 날짜)
    PRIMARY KEY (MEMBER_NO, BK_NO),        -- MEMBER_NO와 BK_NO를 복합 기본 키로 설정
    CONSTRAINT FK_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER (MEMBER_NO),
    CONSTRAINT FK_BOOK_NO FOREIGN KEY (BK_NO) REFERENCES TB_BOOK (BK_NO)
);

--===============================================================================================================================


DROP TABLE TB_MEMBER_BOOK CASCADE CONSTRAINTS;
DROP TABLE TB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE TB_BOOK CASCADE CONSTRAINTS;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEMBER_NO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOOK_NO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE TB_BOOK(
BK_NO NUMBER CONSTRAINT BOOK_PK PRIMARY KEY,
BK_TITLE VARCHAR2(50) CONSTRAINT BOOK_NN_TITLE NOT NULL,
BK_AUTHOR VARCHAR2(20) CONSTRAINT BOOK_NN_AUTHOR NOT NULL,
BK_NUM NUMBER,
BK_PRICE NUMBER,
BK_PUB_NO VARCHAR2(20)
);    

CREATE TABLE TB_MEMBER (
MEMBER_NO NUMBER CONSTRAINT MEMBER_PK PRIMARY KEY, --MEMBER_NO(회원번호) 기본키(MEMBER_PK)
MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_UQ_ID UNIQUE, --MEMBER_ID(아이디)(MEMBER_UQ_ID)
MEMBER_PWD VARCHAR2(20) CONSTRAINT MEMBER_NN_PWD NOT NULL, --MEMBER_PWD(비밀번호)(MEMBER_NN_PWD)
MEMBER_NAME VARCHAR2(20) CONSTRAINT MEMBER_NN_NAME NOT NULL, --MEMBER_NAME(회원명)(MEMBER_NN_NAME)
GENDER CHAR(3) CONSTRAINT MEMBER_CK_GNE CHECK(GENDER IN('M', 'F')), --GENDER(성별)(MEMBER_CK_GEN)
ADDRESS VARCHAR(50), --ADDRESS(주소)
PHONE VARCHAR(13), -- PHONE(연락처)
ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL --ENROLL_DATE(가입일) (MEMBER_NN_EN)
);
            
CREATE TABLE TB_MEMBER_BOOK (
    MEMBER_NO NUMBER,                      -- 회원 번호 (FK)
    BK_NO NUMBER,                          -- 도서 번호 (FK)
    PURCHASE_DATE DATE DEFAULT SYSDATE,     -- 구매 일자 (기본 값: 현재 날짜)
    PRIMARY KEY (MEMBER_NO, BK_NO),        -- MEMBER_NO와 BK_NO를 복합 기본 키로 설정
    CONSTRAINT FK_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER (MEMBER_NO) ON DELETE CASCADE, 
    CONSTRAINT FK_BOOK_NO FOREIGN KEY (BK_NO) REFERENCES TB_BOOK (BK_NO)ON DELETE CASCADE
);
-- 회원 번호 자동 증가 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 도서 번호 자동 증가 시퀀스 생성
CREATE SEQUENCE SEQ_BOOK_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO TB_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass1234', '김철수', 'M', '서울시 강남구', '010-1234-5678', SYSDATE);
INSERT INTO TB_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user02', 'password', '이영희', 'F', '부산시 해운대구', '010-5678-1234', SYSDATE);
INSERT INTO TB_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user03', 'mypwd789', '박민준', 'M', '대전시 중구', '010-7777-8888', SYSDATE);
INSERT INTO TB_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'administrator', 'administrator', '관리자', 'M', '서울시 종로구', '010-9999-9999', SYSDATE);

INSERT INTO TB_BOOK VALUES (SEQ_BOOK_NO.NEXTVAL, 'Java Programming', 'Author A', 10, 20000, 'PUB001');
INSERT INTO TB_BOOK VALUES (SEQ_BOOK_NO.NEXTVAL, 'Python Basics', 'Author B', 15, 15000, 'PUB002');
INSERT INTO TB_BOOK VALUES (SEQ_BOOK_NO.NEXTVAL, 'Database Systems', 'Author C', 20, 25000, 'PUB003');
INSERT INTO TB_BOOK VALUES (SEQ_BOOK_NO.NEXTVAL, 'Data Structures', 'Author D', 12, 18000, 'PUB004');
INSERT INTO TB_BOOK VALUES (SEQ_BOOK_NO.NEXTVAL, 'Machine Learning', 'Author E', 8, 30000, 'PUB005');


commit; 

SELECT MEMBER_ID, MEMBER_PWD FROM TB_MEMBER WHERE MEMBER_ID = 'user01';
SELECT MEMBER_NAME FROM TB_MEMBER WHERE MEMBER_ID = 'user01' AND MEMBER_PWD = 'pass1234';